### ISSUE TITLE
Please add a license for permission.

### ISSUE THREAD

**Issue by Poikilos** [BlainMaguire/carboxyl#1]
Please add a license because: https://choosealicense.com/no-permission/

The easy way is:
- Log into GitHub, go to BlainMaguire/carboxyl
- Add File, Create New File
  - Change the name to license.txt and GitHub's license chooser button will appear:
    - Click the "Choose a license template" button that appeared on the right then choose the one you want (You should choose MIT License or one compatible with that since you say you used code from https://github.com/fogleman/Minecraft) and add your name (and Michael Fogleman who made the project from which you say you got the camera code) and the year if not auto-filled.
  - Change the branch to (commit directly to) "master" at the bottom.
  - Click "Commit new file"

**Comment by BlainMaguire** [comment]
I've added an MIT license 887d6d509e3bc884cde3e9b31774070076ca003e.
